export const GIDER_KATEGORILERI = [
  { text: '1. İMALAT GİDERİ', color: 'cyan' },
  { text: '1. PARTİ GİDERİ', color: 'orange' },
  { text: '2. PARTİ GİDERİ', color: 'orange' },
  { text: '3. PARTİ GİDERİ', color: 'orange' },
  { text: 'ÇALIŞAN GİDERİ', color: 'red' },
  { text: 'DİĞER GİDERLER', color: 'purple' },
  { text: 'DÜKKAN KURULUM GİDERİ', color: 'purple' },
  { text: 'E-TİCARET STOPAJI', color: 'yellow' },
  { text: 'ENTEGRASYONLAR', color: 'yellow' },
  { text: 'FAİZ', color: 'green' },
  { text: 'HİZMET BEDELİ', color: 'cyan' },
  { text: 'İMALAT GİDERİ', color: 'green' },
  { text: 'KARGO GİDERİ', color: 'red' },
  { text: 'MASRAF TAHSİLATI', color: 'orange' },
  { text: 'MATBAA', color: 'blue' },
  { text: 'MUHASEBE / GÜMRÜK', color: 'purple' },
  { text: 'OFİS GİDERİ', color: 'blue' },
  { text: 'PAKETLEME GİDERİ', color: 'orange' },
  { text: 'PLATFORM HİZMET BEDELİ', color: 'yellow' },
  { text: 'REKLAM GİDERİ', color: 'orange' },
  { text: 'TRENDYOL KOMİSYONU', color: 'green' },
  { text: 'ULAŞIM GİDERİ', color: 'green' },
] as const;

export const ETIKETLER = [
  { text: 'BOŞ', color: 'gray' },
  { text: '(KADIN) BLUZ', color: 'gray' },
  { text: 'AYAKKABI KUTUSU', color: 'gray' },
  { text: 'BEBEK', color: 'gray' },
  { text: 'KARGO POŞETİ', color: 'gray' },
  { text: 'BANKA MASRAF TAHSİLATI', color: 'gray' },
  { text: 'HEDİYE ÇEKİ', color: 'gray' },
  { text: '1. HAZİRAN DÖNEMİ', color: 'gray' },
  { text: 'NAKLİYE', color: 'gray' },
  { text: '1. PARTİ ÜRETİM', color: 'gray' },
  { text: 'TRENDYOL YURTİÇİ KARGO BEDELİ', color: 'gray' },
  { text: 'ÜRETİM SÜRECİNDEKİ KUMAŞ, AKSESUAR, İŞÇİLİK', color: 'gray' },
  { text: 'MAAŞ, SGK, PRİM, YEMEK, YOL YARDIMI', color: 'gray' },
  { text: '2. PARTİ ÜRETİM', color: 'gray' },
  { text: 'TRENDYOL SPONSORLU ÜRÜN REKLAMI', color: 'gray' },
  { text: 'KARGO FİRMALARINA ÖDENEN GÖNDERİM BEDELLERİ', color: 'gray' },
  { text: 'AMBALAJ, ETİKET, KUTU, POŞET VB.', color: 'gray' },
  { text: 'KİRA, ELEKTRİK, SU, DOĞALGAZ, İNTERNET', color: 'gray' },
  { text: 'MUHASEBECİ ÜCRETİ, E-FATURA KONTÖRÜ', color: 'gray' },
  { text: 'MAĞAZA AÇILIŞI, TADİLAT, DEKORASYON', color: 'gray' },
  { text: 'DİĞER', color: 'gray' },
] as const;

export const SATIS_KATEGORILERI = [
  { text: 'DİĞER GELİRLER', color: 'purple' },
  { text: 'İADE / İPTAL', color: 'red' },
  { text: 'TRENDYOL SATIŞ GELİRİ', color: 'blue' },
] as const;
